#ifndef MOUSE_BUTTON_CODES_H
#define MOUSE_BUTTON_CODES_H

// From glfw3.h
#define ORG_MOUSE_BUTTON_1         0
#define ORG_MOUSE_BUTTON_2         1
#define ORG_MOUSE_BUTTON_3         2
#define ORG_MOUSE_BUTTON_4         3
#define ORG_MOUSE_BUTTON_5         4
#define ORG_MOUSE_BUTTON_6         5
#define ORG_MOUSE_BUTTON_7         6
#define ORG_MOUSE_BUTTON_8         7
#define ORG_MOUSE_BUTTON_LAST      ORG_MOUSE_BUTTON_8
#define ORG_MOUSE_BUTTON_LEFT      ORG_MOUSE_BUTTON_1
#define ORG_MOUSE_BUTTON_RIGHT     ORG_MOUSE_BUTTON_2
#define ORG_MOUSE_BUTTON_MIDDLE    ORG_MOUSE_BUTTON_3

#endif // MOUSE_BUTTON_CODES_H