<!-- Src/OrangeScript/OrangeScript-Core.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <!-- 输出到项目根目录的 out/Scripts -->
    <OutputPath>$(MSBuildThisFileDirectory)../../../out/Scripts</OutputPath>
    <IntermediateOutputPath>$(MSBuildThisFileDirectory)../../../Build/OrangeScript/Intermediates</IntermediateOutputPath>
  </PropertyGroup>
</Project>